Repository stevelonny/jujutracer, pull requests merged in 2025-05, with the labels that each got.

#13 Fixing issue #12
  src/shapes.jl
  test/runtests.jl
Labels: ready-for-merge

#14 Fixing write_pfm_image issue #9
  demo.jl
  src/inputoutput.jl
Labels: ready-for-merge

#15 Flat Renderer
  CHANGELOG.md
  README.md
  demo.jl
  src/brdf.jl
  src/jujutracer.jl
  src/renderer.jl
  src/shapes.jl
  test/runtests.jl
Labels: enhancement, ready-for-merge

#17 Implement of random number generator - PCG
  CHANGELOG.md
  src/jujutracer.jl
  src/randgen.jl
  test/runtests.jl
Labels: enhancement, ready-for-merge

#18 New Shapes
  CHANGELOG.md
  demoShape.jl
  src/jujutracer.jl
  src/meshes.jl
  src/shapes.jl
  test/runtests.jl
Labels: enhancement

#27 Fix copysing in ONB, fix ray_intersection_list(box)
  src/camera.jl
  src/csg.jl
  src/geometry.jl
  src/jujutracer.jl
  src/shapes.jl
  test/runtests.jl
Labels: bug, ready-for-merge
