Repository stevelonny/jujutracer, pull requests merged in 2025-06, with the labels that each got.

#23 Newshapes
  CHANGELOG.md
  README.md
  all_flat_800x450_2aa.png
  all_path_800x450_3rays_3depth_2rus_2aa.png
  demoAll.jl
  demoCSG.jl
  src/brdf.jl
  src/jujutracer.jl
  src/renderer.jl
  src/shapes.jl
  src/shapes/aabb.jl
  src/shapes/abstractshapes.jl
  src/shapes/csg.jl
  src/shapes/flatcircle.jl
  src/shapes/flatplane.jl
  src/shapes/flatrectangle.jl
  src/shapes/hitrecord.jl
  src/shapes/meshes.jl
  src/shapes/shapes.jl
  src/shapes/solidbox.jl
  src/shapes/solidcone.jl
  src/shapes/solidcylinder.jl
  src/shapes/solidsphere.jl
  src/shapes/templateflat.jl
  src/shapes/templatesolid.jl
  src/shapes/world.jl
  test/runtests.jl
Labels: enhancement, ready-for-merge

#30 Point-light tracing
  CHANGELOG.md
  Project.toml
  README.md
  allFlat.png
  allPath.png
  allPoint.png
  all_flat_800x450_2aa.png
  all_path_800x450_3rays_3depth_2rus_2aa.png
  demoAll.jl
  src/brdf.jl
  src/imagetracer.jl
  src/inputoutput.jl
  src/jujutracer.jl
  src/renderer.jl
  src/shapes/aabb.jl
  src/shapes/abstractshapes.jl
  src/shapes/csg.jl
  src/shapes/flatcircle.jl
  src/shapes/flatplane.jl
  src/shapes/flatrectangle.jl
  src/shapes/light.jl
  src/shapes/meshes.jl
  src/shapes/shapes.jl
  src/shapes/solidbox.jl
  src/shapes/solidcone.jl
  src/shapes/solidcylinder.jl
  src/shapes/solidsphere.jl
  src/shapes/templateflat.jl
  src/shapes/templatesolid.jl
  src/shapes/world.jl
  test/runtests.jl
Labels: enhancement

#41 Fix issue #40
  docs/src/scene/interpreter.md
  interpreter.jl
Labels: enhancement

#45 Patch release: up docstrings, squash bugs, enhance cli interface
  CHANGELOG.md
  asset/allFlat.png
  asset/allPath.png
  asset/allPoint.png
  asset/tree.png
  asset/tree_box.png
  docs/src/scene/interpreter.md
  interpreter.jl
  scenes/scene.md
  scenes/tree.txt
  scenes/tree_box.txt
  src/brdf.jl
  src/hdrimg.jl
  src/renderer.jl
  src/shapes/light.jl
  src/shapes/meshes.jl
  src/shapes/solidbox.jl
Labels: bug, documentation, enhancement
